default:
  owner: 'airflow'
  depends_on_past: false
  start_date: 2023-01-01
  email_on_failure: false
  email_on_retry: false
  retries: 1
  retry_delay_sec: 300

Producer:
  description: 'Demonstrates dataset changes'
  schedule_interval: '@daily'
  max_active_runs: 1
  catchup: false
  tags: ['example', 'dataset', 'producer', 'dag-factory']

  tasks:
    update_dataset:
      operator: airflow.operators.python.PythonOperator
      python_callable_name: update_dataset
      python_callable_file: /opt/airflow/dags/producer/producer_functions.py
      # Note: Dataset outlets need to be handled in the Python function or through custom configuration
